### ISSUE TITLE
personnaliser le message du tweet en fonction du genre (H/F)

### ISSUE THREAD

**Issue by rcadel** [hulk-devfest2017/tweetmodule#11]

**Comment by agarbe** [comment]
D'apres la spec (trello) il n'y a pas le genre dans le message de résultat donc ça va être difficile ...

**Comment by rcadel** [comment]
dans la gateway on voit ça https://github.com/hulk-devfest2017/arduino-gateway/blob/9f1f72828d1d2d9a957996768da63e44da13ecc7/application/arduinogateway.js#L63

donc on retransmets l'ensemble des infos en provenance du joueur et dans le trello on voit qu'il y a confusion entre les deux derniers message de karim donc tu devrais avoir genderMale dans le json
